# rectangle formation yaml
# global goal setting
global_goal:
  swarm_central_pos: { x: 25.0, y: 0.0, z: 1.0 }
  swarm_scale: 2.5
  s0: { x: 0.000, y: 0.00, z: 0.0 }
  s1: { x: 0.8025, y: 0.7474, z: 0.0 }
  s2: { x: -0.0104, y: 1.5182, z: 0.0 }
  s3: { x: -0.7852, y: 0.7358, z: 0.0 }
  s4: { x: 0.7694, y: -0.7591, z: 0.0 }
  s5: { x: -0.0021, y: -1.4949, z: 0.0 }
  s6: { x: -0.7652, y: -0.7474, z: 0.0 }

  y0: { x: -0.4915, y: 0.5139, z: 0.0 }
  y1: { x: 0.52, y: 0.5022, z: 0.0 }
  y2: { x: 1.0182, y: 1.1161, z: 0.0 }
  y3: { x: -1.0058, y: 1.1277, z: 0.0 }
  y4: { x: -0.0021, y: -0.6774, z: 0.0 }
  y5: { x: 0.0062, y: -1.4715, z: 0.0 }
  y6: { x: 0.000, y: 0.00, z: 0.0 }

  u0: { x: -0.9975, y: 0.4788, z: 0.0 }
  u1: { x: 0.9850, y: 0.5139, z: 0.0 }
  u2: { x: 1.0099, y: 1.5299, z: 0.0 }
  u3: { x: -0.9809, y: 1.5182, z: 0.0 }
  u4: { x: 0.8523, y: -0.9927, z: 0.0 }
  u5: { x: 0.0228, y: -1.2380, z: 0.0 }
  u6: { x: -0.7569, y: -0.9927, z: 0.0 }

# map_size_x          : 70.0
# map_size_y          : 30.0
# map_size_z          : 3.0
optimization:
  formation_type: 1
  weight_obstacle: 50000.0
  weight_swarm: 50000.0
  weight_feasibility: 10000.0
  weight_sqrvariance: 10000.0
  weight_time: 80.0
  weight_formation: 15000.0
  obstacle_clearance: 0.5
  swarm_clearance: 0.5

fsm:
  replan_trajectory_time: 0.1 # s, the max time of replanning trajectory
